/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.core.Icon");jQuery.sap.require("sap.ui.core.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.core.Icon",{metadata:{library:"sap.ui.core",properties:{"src":{type:"sap.ui.core.URI",group:"Misc",defaultValue:null},"size":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"color":{type:"string",group:"Misc",defaultValue:null},"hoverColor":{type:"string",group:"Misc",defaultValue:null},"activeColor":{type:"string",group:"Misc",defaultValue:null},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"backgroundColor":{type:"string",group:"Misc",defaultValue:null},"hoverBackgroundColor":{type:"string",group:"Misc",defaultValue:null},"activeBackgroundColor":{type:"string",group:"Misc",defaultValue:null}},events:{"press":{}}}});sap.ui.core.Icon.M_EVENTS={'press':'press'};jQuery.sap.require("sap.ui.core.IconPool");(function(){var t=(jQuery.sap.touchEventMode==="OFF"),a=(t?"onmousedown":"ontouchstart"),c=(t?"onclick":"ontap");sap.ui.core.Icon.prototype[a]=function(e){if(e.srcControl.mEventRegistry["press"]||e.srcControl.mEventRegistry["tap"]){e.originalEvent._sapui_handledByControl=true}var A=this.getActiveColor(),s=this.getActiveBackgroundColor(),$;if(A||s){if((e.targetTouches&&e.targetTouches.length===1)||!e.targetTouches){$=this.$();$.addClass("sapUiIconActive");if(A){$.css("color",A)}if(s){$.css("background-color",s)}this._isActiveState=true;if(!this._touchEndProxy){this._touchEndProxy=jQuery.proxy(this._ontouchend,this)}if(!jQuery.support.touch){jQuery(window.document).bind("mouseup",this._touchEndProxy)}else{this.$().bind("touchcancel touchend",this._touchEndProxy)}}}};sap.ui.core.Icon.prototype[c]=function(e){this.firePress({})};if(t){sap.ui.core.Icon.prototype.onmouseover=function(e){var h=this.getHoverColor(),H=this.getHoverBackgroundColor(),$=this.$();if(h){$.css("color",h)}if(H){$.css("background-color",H)}};sap.ui.core.Icon.prototype.onmouseout=function(e){if(!this._isActiveState){this._restoreColors()}}}}());
sap.ui.core.Icon.prototype._ontouchend=function(e){if((e.targetTouches&&e.targetTouches.length===0)||!e.targetTouches){this._isActiveState=false;this.$().removeClass("sapUiIconActive");this._restoreColors();if(!jQuery.support.touch){jQuery(window.document).unbind("mouseup",this._touchEndProxy)}else{this.$().unbind("touchcancel touchend",this._touchEndProxy)}}};
sap.ui.core.Icon.prototype._restoreColors=function(){this.$().css({"color":this.getColor()||"","background-color":this.getBackgroundColor()||""})};
sap.ui.core.Icon.prototype.setSrc=function(s){this.setProperty("src",s,true);var i=sap.ui.core.IconPool.getIconInfo(s),t=(jQuery.browser.msie&&jQuery.browser.fVersion<9),$=this.$();if(i){$.css("font-family",i.fontFamily);if(t){$.text(i.content)}else{$.attr("data-sap-ui-icon-content",i.content)}}};
sap.ui.core.Icon.prototype.setWidth=function(w){this.setProperty("width",w,true);this.$().css("width",w)};
sap.ui.core.Icon.prototype.setHeight=function(h){this.setProperty("height",h,true);this.$().css({"height":h,"line-height":h})};
sap.ui.core.Icon.prototype.setSize=function(s){this.setProperty("size",s,true);this.$().css("font-size",s)};
sap.ui.core.Icon.prototype.setColor=function(c){this.setProperty("color",c,true);this.$().css("color",c)};
sap.ui.core.Icon.prototype.setActiveColor=function(c){this.setProperty("activeColor",c,true)};
sap.ui.core.Icon.prototype.setHoverColor=function(c){this.setProperty("hoverColor",c,true)};
sap.ui.core.Icon.prototype.setBackgroundColor=function(c){this.setProperty("backgroundColor",c,true);this.$().css("background-color",c)};
sap.ui.core.Icon.prototype.setActiveBackgroundColor=function(c){this.setProperty("activeBackgroundColor",c,true)};
sap.ui.core.Icon.prototype.setHoverBackgroundColor=function(c){this.setProperty("hoverBackgroundColor",c,true)};
