/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.commons.FormColumnLayoutRenderer");jQuery.sap.require("sap.ui.commons.FormLayoutRenderer");sap.ui.commons.FormColumnLayoutRenderer=sap.ui.core.Renderer.extend(sap.ui.commons.FormLayoutRenderer);
sap.ui.commons.FormColumnLayoutRenderer.render=function(r,l){var a=r};
sap.ui.commons.FormColumnLayoutRenderer.renderForm=function(r,l,f){this.renderTitle(r,f.getTitle(),f.getId(),false);var c=l.getColumns();r.write("<DIV");r.addClass("sapUiFormColumnLayoutFlex");r.writeClasses();r.write(">");var C=f.getFormContainers();for(var i=0;i<c;i++){r.write("<DIV");r.addClass("sapUiFormColumnLayoutCol");r.writeClasses();r.write(">");var C=f.getFormContainers();for(var j=i,a=C.length;j<a;j=j+c){var o=C[j];var b=sap.ui.getCore().byId(o.getLayout());if(b&&b.getMetadata().getName()!=l.getMetadata().getName()){b.getRenderer().renderContainer(r,b,o)}else{this.renderContainer(r,b,o)}}r.write("</DIV>")}r.write("</DIV>")};
sap.ui.commons.FormColumnLayoutRenderer.renderContainer=function(r,L,c){var e=false;r.write("<section");r.writeElementData(c);r.addClass("sapUiFormContainer");r.addClass(L.getClass());switch(c.getType()){case sap.ui.commons.FormContainerType.Border:r.addClass("sapUiFormContainerBorder");break;case sap.ui.commons.FormContainerType.Expandable:r.addClass("sapUiFormContainerExp");e=true;break;default:break}if(c.getTooltip_AsString()){r.writeAttributeEscaped('title',c.getTooltip_AsString())}r.writeClasses();r.write(">");this.renderTitle(r,c.getTitle(),c.getId(),e);var C=L.getColumns();r.write("<div id='"+c.getId()+"-content'");r.addClass("sapUiFormColumnLayoutFlex");r.writeClasses();if(e){if(!c.getExpanded()){r.writeStyle("display","none");r.addStyles()}}r.write(">");for(var k=0;k<C;k++){r.write("<DIV");r.addClass("sapUiFormColumnLayoutCol");r.writeClasses();r.write(">");var E=c.getFormElements();for(var l=k,a=E.length;l<a;l=l+C){var o=E[l];this.renderElement(r,L,o)}r.write("</div>")}r.write("</div></section>")};
