/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.commons.form.SimpleForm");jQuery.sap.require("sap.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.commons.form.SimpleForm",{metadata:{library:"sap.ui.commons",properties:{"maxContainerCols":{type:"int",group:"Appearance",defaultValue:2},"minWidth":{type:"int",group:"Appearance",defaultValue:-1},"editable":{type:"boolean",group:"Misc",defaultValue:null},"labelMinWidth":{type:"int",group:"Misc",defaultValue:192}},defaultAggregation:"content",aggregations:{"content":{type:"sap.ui.core.Element",multiple:true,singularName:"content"},"form":{type:"sap.ui.commons.form.Form",multiple:false,visibility:"hidden"}}}});jQuery.sap.require("sap.ui.commons.form.Form");jQuery.sap.require("sap.ui.commons.form.FormContainer");jQuery.sap.require("sap.ui.commons.form.FormElement");jQuery.sap.require("sap.ui.commons.form.ResponsiveLayout");jQuery.sap.require("sap.ui.commons.layout.ResponsiveFlowLayoutData");
sap.ui.commons.form.SimpleForm.prototype.init=function(){this._iCurrentWidth=0;this._bUpdateNeeded=true;var f=new sap.ui.commons.form.Form();f.setLayout(new sap.ui.commons.form.ResponsiveLayout());this.setAggregation("form",f);this._aElements=null;this._aLayouts=[];var t=this;this.fHandleContentChange=function(e){if(e.getParameter("name")=="visible"){t.invalidate()}}};
sap.ui.commons.form.SimpleForm.prototype.onBeforeRendering=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}this._updateFormContainers()};
sap.ui.commons.form.SimpleForm.prototype.onAfterRendering=function(){this.getDomRef().style.visibility="hidden";setTimeout(jQuery.proxy(this._applyLinebreaks,this),10);this._sResizeListenerId=sap.ui.core.ResizeHandler.register(this.getDomRef(),jQuery.proxy(this._resize,this))};
sap.ui.commons.form.SimpleForm.prototype.invalidate=function(){sap.ui.core.Control.prototype.invalidate.apply(this,arguments);this._bUpdateNeeded=true};
sap.ui.commons.form.SimpleForm.prototype.exit=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);this._sResizeListenerId=null}for(var i=0;i<this._aLayouts.length;i++){this._aLayouts[i].destroy()}};
sap.ui.commons.form.SimpleForm.prototype.indexOfAggregation=function(a,o){if(a=="content"){var c=this._aElements;if(c){for(var i=0;i<c.length;i++){if(c[i]==o){return i}}}return-1}else{return sap.ui.core.Control.prototype.indexOfAggregation.apply(this,arguments)}};
sap.ui.commons.form.SimpleForm.prototype.addContent=function(e,s){if(this._aElements){sap.ui.core.Control.prototype.setAggregation.apply(this,["content",this._aElements,true])}sap.ui.core.Control.prototype.addAggregation.apply(this,["content",e,true]);if(!s){this.invalidate()}return this};
sap.ui.commons.form.SimpleForm.prototype.insertContent=function(e,i,s){if(this._aElements){sap.ui.core.Control.prototype.setAggregation.apply(this,["content",this._aElements,true])}sap.ui.core.Control.prototype.insertAggregation.apply(this,["content",e,i,true]);this._aElements=sap.ui.core.Control.prototype.getAggregation.apply(this,["content"]);if(!s){this.invalidate()}return this};
sap.ui.commons.form.SimpleForm.prototype.removeContent=function(e,s){if(this._aElements){for(var i=0;i<this._aElements.length;i++){if(e==this._aElements[i]){this._aElements.splice(i,1);if(!s){this.invalidate()}if(e&&e.getVisible){e.detachEventOnce("_change",this.fHandleContentChange,this)}return e}}}return null};
sap.ui.commons.form.SimpleForm.prototype.getContent=function(){if(!this._aElements){this._aElements=sap.ui.core.Control.prototype.getAggregation.apply(this,["content"])}return this._aElements};
sap.ui.commons.form.SimpleForm.prototype._hasVisibleFields=function(e){if(!e)return false;var f=e.getFields(),v=false;for(var i=0;i<f.length;i++){var F=f[0];if(F&&F.getVisible&&F.getVisible()){return true}}return false};
sap.ui.commons.form.SimpleForm.prototype._updateFormContainers=function(){if(!this._bUpdateNeeded)return;var c=this.getContent(),C=null,o=null,a=false,f=this.getAggregation("form");if(this._aElements){for(var i=0;i<this._aElements.length;i++){var e=this._aElements[i];if(e&&e.getVisible){e.attachEventOnce("_change",this.fHandleContentChange,this)}if(e&&e.getParent()&&e.getParent()!=this){var p=e.getParent(),A=p.getMetadata().getManagedAggregation(e.sParentAggregationName);if(A.multiple){p.removeAggregation(e.sParentAggregationName,e)}else{p.setAggregation(e.sParentAggregationName,null)}}}}f.destroyFormContainers();for(var i=0;i<c.length;i++){var b=c[i];if(b instanceof sap.ui.commons.Title){C=this._addFormContainer(f,b)}else if(b.getMetadata().isInstanceOf("sap.ui.core.Label")){if(!C){C=this._addFormContainer(f)}if(o){if(this._hasVisibleFields(o)){o.setVisible(true)}else{o.setVisible(false)}if(!a){this._applyFieldWeight(o)}}a=false;o=this._addFormElement(C,b)}else{if(!o){o=this._addFormElement(C)}if(b.getLayoutData()instanceof sap.ui.commons.layout.ResponsiveFlowLayoutData&&!this._isMyLayoutData(b.getLayoutData())){if(b.getLayoutData().getLinebreak()){if(o){this._applyFieldWeight(o)}o=this._addFormElement(C);a=true}}else{b.setLayoutData(this._createLayoutData(5,false,true))}o.addField(b)}if(o){if(this._hasVisibleFields(o)){o.setVisible(true)}else{o.setVisible(false)}if(!a){this._applyFieldWeight(o)}}}this._bUpdateNeeded=false};
sap.ui.commons.form.SimpleForm.prototype._isMyLayoutData=function(l){var i=l.getId(),L=" "+this._aLayouts.join(" ")+" ";return L.indexOf(" "+i+" ")>-1};
sap.ui.commons.form.SimpleForm.prototype._createLayoutData=function(w,l,L){var o=new sap.ui.commons.layout.ResponsiveFlowLayoutData({weight:w,linebreak:l===true,linebreakable:L===true});this._aLayouts.push(o.getId());return o};
sap.ui.commons.form.SimpleForm.prototype._addFormElement=function(f,l){var e=new sap.ui.commons.form.FormElement();e.setLayoutData(new sap.ui.commons.layout.ResponsiveFlowLayoutData({linebreak:true,margin:false}));if(l){l.addStyleClass("sapUiFormLabel-CTX");e.setLabel(l);l.setLayoutData(new sap.ui.commons.layout.ResponsiveFlowLayoutData({weight:3,minWidth:this.getLabelMinWidth()}))}e.setVisible(false);f.addFormElement(e);return e};
sap.ui.commons.form.SimpleForm.prototype._addFormContainer=function(f,t){var c=new sap.ui.commons.form.FormContainer();c.setLayoutData(new sap.ui.commons.layout.ResponsiveFlowLayoutData({minWidth:280}));f.addFormContainer(c);if(t){c.setTitle(t)}return c};
sap.ui.commons.form.SimpleForm.prototype._applyFieldWeight=function(e){var f=e.getFields(),w=Math.floor(5/f.length),r=5%f.length;for(var i=0;i<f.length;i++){var F=f[i],c=w,l=F.getLayoutData();if(i==f.length-1){c+=r}if(!l){F.setLayoutData(this._createLayoutData(c,false,i==0))}else if(this._isMyLayoutData(l)){l.setWeight(c)}}};
sap.ui.commons.form.SimpleForm.prototype._applyLinebreaks=function(){var f=this.getAggregation("form"),c=f.getFormContainers();for(var i=1;i<c.length;i++){var C=c[i],l=C.getLayoutData();if(this.$().outerWidth(true)>this.getMinWidth()){if(l.getLinebreak()){l.setLinebreak(false)}if(i%this.getMaxContainerCols()==0){l.setLinebreak(true)}}else{l.setLinebreak(true)}}var t=this;setTimeout(function(){if(t.getDomRef()){t.getDomRef().style.visibility="visible"}},10)};
sap.ui.commons.form.SimpleForm.prototype._resize=function(){if(this._iCurrentWidth==this.$().outerWidth())return;this._iCurrentWidth=this.$().outerWidth();this._applyLinebreaks()};
