/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.ButtonRenderer");sap.m.ButtonRenderer={};
sap.m.ButtonRenderer.render=function(r,b){if(!b.getVisible()){return}var t=b.getType();var w=b.getWidth();var e=b.getEnabled();var E=false;var T="sap_bluecrystal";var s=sap.ui.getCore().getConfiguration().getTheme().toLowerCase();if(s&&((s.indexOf("crystal")>-1)||(s.indexOf("fiori")>-1)||(s.indexOf("sapphire")>-1))){s="sap_bluecrystal"}r.write("<button type=\"button\"");r.writeControlData(b);if(t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtn")}if(s===T){if(!b.getIcon()){if(t!=sap.m.ButtonType.Accept&&t!=sap.m.ButtonType.Reject&&t!=sap.m.ButtonType.Back&&t!=sap.m.ButtonType.Up){r.addClass("sapMBtnPaddingLeft")}if(b.getText()){r.addClass("sapMBtnPaddingRight")}}else{if(b.getIcon()&&b.getText()&&b.getIconFirst()){r.addClass("sapMBtnPaddingRight")}if(b.getIcon()&&b.getText()&&!b.getIconFirst()){r.addClass("sapMBtnPaddingLeft")}}}if(!e){if(t==sap.m.ButtonType.Back||t==sap.m.ButtonType.Up){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t)+"Disabled")}else{if(t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtnDisabled")}}if(s===T){if(t==sap.m.ButtonType.Accept||t==sap.m.ButtonType.Reject||t==sap.m.ButtonType.Emphasized||t==sap.m.ButtonType.Transparent){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t)+"Disabled")}}}else{if(t!=""&&t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t))}}if(b.getIcon()&&!b.getText()&&t!=sap.m.ButtonType.Back){if(!e){r.addClass("sapMBtnIconDisabled")}else{r.addClass("sapMBtnIcon")}}if(w!=""||w.toLowerCase()=="auto"){E=false;r.writeAttribute("style","width:"+w+";")}r.writeClasses();var a=b.getTooltip_AsString();if(a){r.writeAttributeEscaped("title",a)}r.write(">");if(this.renderButtonContentBefore){this.renderButtonContentBefore(r,b)}if(t==sap.m.ButtonType.Accept){E=true}if(t==sap.m.ButtonType.Reject){E=true}if(t==sap.m.ButtonType.Up){E=true}if(s===T&&t==sap.m.ButtonType.Back){E=true}if(b.getIcon()){E=true}if(E){r.write("<div");if(t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtnContent");r.writeClasses()}r.write(">")}var A=sap.ui.core.IconPool.getIconURI("accept");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Accept,A);var R=sap.ui.core.IconPool.getIconURI("decline");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Reject,R);if(s===T){var B=sap.ui.core.IconPool.getIconURI("nav-back");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Back,B);this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Up,B)}else{var u=sap.ui.core.IconPool.getIconURI("navigation-left-arrow");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Up,u)}if(b.getIcon()&&b.getIconFirst()){this.writeImgHtml(r,b)}this.writeTextHtml(r,b,E,t);if(b.getIcon()&&!b.getIconFirst()){this.writeImgHtml(r,b)}if(E){r.write("</div>")}if(this.renderButtonContentAfter){this.renderButtonContentAfter(r,b)}r.write("</button>")};
sap.m.ButtonRenderer.writeTextHtml=function(r,b,e,t){r.write("<span");if(!e&&t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtnContent");r.writeClasses()}if(b.getIcon()&&b.getText()){r.addClass("sapMBtnContentSpan");r.writeClasses()}r.write(">");if(b.getText()){r.writeEscaped(b.getText())}else{if(t==sap.m.ButtonType.Back){r.write("&nbsp;")}}r.write("</span>")};
sap.m.ButtonRenderer.writeImgHtml=function(r,b){r.renderControl(b._getImage((b.getId()+"-img"),b.getIcon(),b.getActiveIcon(),b.getIconDensityAware()))};
sap.m.ButtonRenderer.writeInternalIconPoolHtml=function(r,b,t,c,u){if(t===c){if(b._imageBtn){b._imageBtn.setSrc(u)}else{r.renderControl(b._getInternalIconBtn((b.getId()+"-iconBtn"),u))}}};
