/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.ColumnListItemRenderer");jQuery.sap.require("sap.ui.core.Renderer");jQuery.sap.require("sap.m.ListRenderer");jQuery.sap.require("sap.m.ListItemBaseRenderer");sap.m.ColumnListItemRenderer=sap.ui.core.Renderer.extend(sap.m.ListItemBaseRenderer);
sap.m.ColumnListItemRenderer.renderLIAttributes=function(r,l){r.addClass("sapMListTblRow")};
sap.m.ColumnListItemRenderer.renderLIContent=function(r,l,L){var c=L.getColumns();l.destroyAggregation("_clonedHeaders",true);if(!L._bRendering){l.removePopin()}l.getCells().forEach(function(C,i){var a,o=c[i];if(!o||!o.getVisible()||o.isNeverVisible(true)||o.isPopin()){return}r.write("<td");r.addClass("sapMListTblCell");r.writeAttribute("id",l.getId()+"_cell"+i);if(o){a=o.getStyleClass(true);a&&r.addClass(a);o.getVAlign()!="Middle"&&r.addStyle("vertical-align",o.getVAlign().toLowerCase());r.addStyle("text-align",o.getCssAlign());r.writeStyles()}r.writeClasses();r.write(">");r.renderControl(o.applyAlignTo(C));r.write("</td>")})};
sap.m.ColumnListItemRenderer.renderPopin=function(r,l,L){l._popinId=l.getId()+"-sub";r.write("<tr class='sapMListTblSubRow'");r.writeAttribute("id",l._popinId);r.write("><td");r.writeAttribute("colspan",L._colCount);r.write("><div class='sapMListTblSubCnt'>");L.getColumns().forEach(function(c,i){if(!c.getVisible()||!c.isPopin()){return}var a=c.getStyleClass(),h=c.getPopinHAlign(),t=c.getCssAlign(h),b=c.getHeader(),d=l.getCells()[i];r.write("<div");r.addClass("sapMListTblSubCntRow");a&&r.addClass(a);r.writeClasses();r.write(">");r.write("<div");r.addStyle("text-align",t);r.addClass("sapMListTblSubCntHdr");r.writeClasses();r.writeStyles();r.write(">");if(b){b=b.clone();l.addAggregation("_clonedHeaders",b,true);c.applyAlignTo(b,h);r.renderControl(b)}r.write("</div>");if(b){r.write("<div class='sapMListTblSubCntSpr'>:</div>")}r.write("<div");r.addStyle("text-align",t);r.addClass("sapMListTblSubCntVal");r.writeClasses();r.writeStyles();r.write(">");if(d){c.applyAlignTo(d,h);r.renderControl(d)}r.write("</div>");r.write("</div>")});r.write("</div></td></tr>")};
