/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.GrowingList");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.m.List");sap.m.List.extend("sap.m.GrowingList",{metadata:{library:"sap.m",properties:{"threshold":{type:"int",group:"Misc",defaultValue:20},"triggerText":{type:"string",group:"Appearance",defaultValue:null},"scrollToLoad":{type:"boolean",group:"Misc",defaultValue:false}}}});
sap.m.GrowingList.prototype.init=function(){if(sap.m.List.prototype.init){sap.m.List.prototype.init.apply(this,arguments)}this._iRenderedDataItems=0;this._trigger=null;this._loading=null;this._loadingByScroll=false;this._countChecked=false;this._iItemCount=0;this._bExperimentalGrouping=false};
sap.m.GrowingList.prototype.onAfterRendering=function(){this._countChecked=false;if(sap.m.List.prototype.onAfterRendering){sap.m.List.prototype.onAfterRendering.apply(this,arguments)}if(this.getScrollToLoad()){var s=sap.m.getScrollDelegate(this);if(s){s.setGrowingList(this,this._triggerLoadingByScroll)}}this._updateTrigger()};
sap.m.GrowingList.prototype.setScrollToLoad=function(s){if(this.getScrollToLoad()&&!s){var S=sap.m.getScrollDelegate(this);if(S){S.setGrowingList(null)}}return this.setProperty("scrollToLoad",s)};
sap.m.GrowingList.prototype.exit=function(){if(sap.m.List.prototype.exit){sap.m.List.prototype.exit.apply(this,arguments)}if(this._busyIndicator){this._busyIndicator.destroy()}if(this._trigger){this._trigger.destroy()}};
sap.m.GrowingList.prototype._getTrigger=function(i){var t=this;var T=sap.ui.getCore().getLibraryResourceBundle("sap.m").getText("LOAD_MORE_DATA");if(this.getTriggerText()){T=this.getTriggerText()}return this._trigger||(this._trigger=new sap.m.CustomListItem({id:i,content:new sap.ui.core.HTML({content:"<div class='sapMGrowingListTrigger'>"+"<div class='sapMGrowingListBusyIndicator' id='"+i+"-busyIndicator'></div>"+"<div class='sapMSLITitleDiv sapMGrowingListTitel'>"+"<h1 class='sapMSLITitle'>"+T+"</h1>"+"</div>"+"<div class='sapMGrowingListDescription'>"+"<p class='sapMSLIDescription' id='"+i+"-itemInfo'>"+t._getListItemInfo()+"</p>"+"</div>"+"</div>",afterRendering:function(e){var b=t._getBusyIndicator();var r=sap.ui.getCore().createRenderManager();r.render(b,this.getDomRef().firstChild);r.destroy()}}),type:sap.m.ListType.Active}).setParent(this,null,true).attachTap(this._tap))};
sap.m.GrowingList.prototype._getLoading=function(i){var t=this;return this._loading||(this._loading=new sap.m.CustomListItem({id:i,content:new sap.ui.core.HTML({content:"<div class='sapMSLIDiv sapMGrowingListLoading'>"+"<div class='sapMGrowingListBusyIndicator' id='"+i+"-busyIndicator'></div>"+"</div>",afterRendering:function(e){var b=t._getBusyIndicator();var r=sap.ui.getCore().createRenderManager();r.render(b,this.getDomRef().firstChild);r.destroy()}})}).setParent(this,null,true))};
sap.m.GrowingList.prototype._getBusyIndicator=function(){return this._busyIndicator||(this._busyIndicator=new sap.m.BusyIndicator({size:"2.0em"}))};
sap.m.GrowingList.prototype._getListItemInfo=function(){return("[ "+this._iRenderedDataItems+" / "+this._getListItemCount()+" ]")};
sap.m.GrowingList.prototype._tap=function(e){var t=this;jQuery.sap.byId(this.getId()+'-busyIndicator').toggleClass('sapMGrowingListBusyIndicatorVisible',true);window.setTimeout(function(){t.oParent._iItemCount+=t.oParent.getThreshold();t.oParent.updateItems()},0)};
sap.m.GrowingList.prototype.addListItem=function(i,s){if(!this._countChecked){this._countChecked=true;if(this.getShowNoData()){jQuery.sap.byId(this.getId()+"-listNoData").css("display","none")}}i._mode=this.getMode();i._includeItemInSelection=this.getIncludeItemInSelection();i._select=this._select;i._delete=this._delete;i._listId=this.getId();i._showUnread=this.getShowUnread();this._iRenderedDataItems++;if(this._bExperimentalGrouping){var b=this.getBinding("items"),g=b.isGrouped()&&this.addItemGroup,n=null,N=false;if(g){n=this._getGroupForContext(i.getBindingContext());if(this.getItems().length==0){N=true}else{var I=this.getItems();if(n.key!==this._getGroupForContext(I[I.length-1].getBindingContext()).key){N=true}}if(N){var G;var B=this.getBindingInfo("items");if(B.groupHeaderFactory){G=B.groupHeaderFactory(n)}this.addItemGroup(n,G)}}}this.addAggregation("items",i,s);if(this._bExperimentalGrouping&&s){var d=jQuery.sap.domById(this.getId()+"-listUl");if(d){var r=sap.ui.getCore().createRenderManager();r.renderControl(i);r.flush(d,false,true);r.destroy()}}return this};
sap.m.GrowingList.prototype.addItemGroup=function(g,h){if(!h){h=new sap.m.GroupHeaderListItem({title:g.text||g.key}).addStyleClass("sapMListHdr")}this.addAggregation("items",h,true);var d=jQuery.sap.domById(this.getId()+"-listUl");if(d){var r=sap.ui.getCore().createRenderManager();r.renderControl(h);r.flush(d,false,true);r.destroy()}};
sap.m.GrowingList.prototype._getGroupForContext=function(c){var n=this.getBinding("items").oSorter.fnGroup(c);if(typeof n=="string"){n={key:n}}return n};
sap.m.GrowingList.prototype.insertListItem=function(i,I){if(!this._countChecked){this._countChecked=true;if(this.getShowNoData()){jQuery.sap.byId(this.getId()+"-listNoData").css("display","none")}}i._mode=this.getMode();i._includeItemInSelection=this.getIncludeItemInSelection();i._select=this._select;i._delete=this._delete;i._listId=this.getId();i._showUnread=this.getShowUnread();this._iRenderedDataItems++;this.insertAggregation("items",i,I,true);var r=sap.ui.getCore().createRenderManager();var l=this.getId()+"-listUl";r.renderControl(i);r.flush(jQuery.sap.domById(l),false,I);r.destroy();return this};
sap.m.GrowingList.prototype.deleteListItem=function(i){this._iRenderedDataItems--;this.removeAggregation("items",i,true);i.destroy();return this};
sap.m.GrowingList.prototype._getListItemCount=function(){var b=this.getBinding("items");if(b){return b.getLength()}else{return this.getItems().length}};
sap.m.GrowingList.prototype.updateItems=function(){if(this._iItemCount==0){this._iItemCount=this.getThreshold()}var b=this.getBindingInfo("items"),f=b.factory,B=b.binding,L=this._getListItemCount(),n=Math.min(L,this.getThreshold()),t=this.getThreshold(),c=B?B.getContexts(0,this._iItemCount):[];this._getBusyIndicator().setVisible(true);if(this._bExperimentalGrouping){var F=true;if(c.length>0){var s=this.getId()+"-listUl";if(jQuery.sap.domById(s)!=undefined||jQuery.sap.domById(s)!=null){if(c.diff){F=false;var a=false;for(var i=0,l=c.diff.length;i<l;i++){var I=this.getAggregation("items");if(c.diff[i].type==="delete"){F=true;break}if(c.diff[i].type==="insert"){if(!a&&c.diff[i].index!==this._iRenderedDataItems){F=true;break}a=true;var C=f("",c[c.diff[i].index]);C.setBindingContext(c[c.diff[i].index],b.model);this.addListItem(C,true)}}}if(F){this.destroyItems();this._iRenderedDataItems=0;for(var i=0,l=c.length;i<l;i++){var C=f("",c[i]);C.setBindingContext(c[i],b.model);this.addListItem(C,false)}}}else{for(var i=0,l=c.length;i<l;i++){var C=f("",c[i]);C.setBindingContext(c[i],b.model);this.addListItem(C,true)}}}else{this._iRenderedDataItems=0;this.destroyItems()}}else{if(c.length>0){var s=this.getId()+"-listUl";if(jQuery.sap.domById(s)!=undefined||jQuery.sap.domById(s)!=null){if(c.diff){for(var i=0,l=c.diff.length;i<l;i++){var I=this.getAggregation("items");if(c.diff[i].type==="delete"){this.deleteListItem(I[c.diff[i].index])}if(c.diff[i].type==="insert"){var C=f("",c[c.diff[i].index]);C.setBindingContext(c[c.diff[i].index],b.model);this.insertListItem(C,c.diff[i].index)}}}else{this._iRenderedDataItems=0;this.destroyItems();for(var i=0,l=c.length;i<l;i++){var C=f("",c[i]);C.setBindingContext(c[i],b.model);this.addListItem(C,false)}}}else{for(var i=0,l=c.length;i<l;i++){var C=f("",c[i]);C.setBindingContext(c[i],b.model);this.addListItem(C,true)}}}else{this._iRenderedDataItems=0;this.destroyItems()}}this._hideIndicator();var m=this._iRenderedDataItems+this.getThreshold();if(this._iItemCount>m){this._iItemCount=m}this._updateTrigger()};
sap.m.GrowingList.prototype._updateTrigger=function(){var m=this._getListItemCount();if(this._iItemCount>=m){jQuery.sap.byId(this.getId()+"-triggerList").css("display","none")}else{jQuery.sap.byId(this.getId()+"-triggerList").css("display","block")}};
sap.m.GrowingList.prototype._hideIndicator=function(){var t=this,i=t.getId(),$=jQuery.sap.byId;window.setTimeout(function(){if(t.getScrollToLoad()){$(i+'-triggerList').css("display","none");t._loadingByScroll=false}else{$(i+'-trigger-itemInfo').html(t._getListItemInfo());$(i+'-trigger-busyIndicator').toggleClass('sapMGrowingListBusyIndicatorVisible',false)}t._getBusyIndicator().setVisible(false)},0)};
sap.m.GrowingList.prototype._triggerLoadingByScroll=function(){if(!this._loadingByScroll){jQuery.sap.byId(this.getId()+'-triggerList').css("display","block");this._getBusyIndicator().setVisible(true);this._loadingByScroll=true;this._iItemCount+=this.getThreshold();this.updateItems()}};
sap.m.GrowingList.prototype.bUseExtendedChangeDetection=true;
