/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Input");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.m.InputBase");sap.m.InputBase.extend("sap.m.Input",{metadata:{library:"sap.m",properties:{"type":{type:"sap.m.InputType",group:"Data",defaultValue:sap.m.InputType.Text},"maxLength":{type:"int",group:"Behavior",defaultValue:0},"valueStateText":{type:"string",group:"Misc",defaultValue:null},"showValueStateMessage":{type:"boolean",group:"Misc",defaultValue:true},"dateFormat":{type:"string",group:"Misc",defaultValue:'YYYY-MM-dd',deprecated:true}},events:{"liveChange":{}}}});sap.m.Input.M_EVENTS={'liveChange':'liveChange'};jQuery.sap.require("sap.ui.core.EnabledPropagator");jQuery.sap.require("sap.ui.core.IconPool");sap.ui.core.IconPool.insertFontFaceStyle();
sap.m.Input.prototype.init=function(){sap.m.InputBase.prototype.init.call(this);this._inputProxy=jQuery.proxy(this._onInput,this)};
sap.m.Input.prototype.onAfterRendering=function(){sap.m.InputBase.prototype.onAfterRendering.call(this);this._$input.bind("input.input",this._inputProxy)};
sap.m.Input.prototype._onInput=function(e){var v=this._$input.val();this.setProperty("value",v,true);this._setLabelVisibility();this.fireLiveChange({newValue:v})};
(function(){function c(i){if(i._popup){i._popup.close()}};function o(i){var s=i.getValueState();if(i.getShowValueStateMessage()&&s&&((s===sap.ui.core.ValueState.Warning)||(s===sap.ui.core.ValueState.Error))&&i.getEnabled()&&i.getEditable()){var t=i.getValueStateText();if(!t){t=sap.ui.core.ValueStateSupport.getAdditionalText(i)}if(!t){return}var m=i.getId()+"-message";if(!i._popup){jQuery.sap.require("sap.ui.core.Popup");jQuery.sap.require("jquery.sap.encoder");i._popup=new sap.ui.core.Popup("<span></span>",false,false,false);i._popup.attachClosed(function(){jQuery.sap.byId(m).remove()})}var I=jQuery(i.getFocusDomRef());var d=sap.ui.core.Popup.Dock;var b=I.css("text-align")==="right";var C="sapMInputMessage "+((s===sap.ui.core.ValueState.Warning)?"sapMInputMessageWarning":"sapMInputMessageError");i._popup.setContent(jQuery("<div style=\"max-width:"+I.outerWidth()+"px;\" class=\""+C+"\" id=\""+m+"\"><span id=\""+m+"-text\">"+jQuery.sap.encodeHTML(t)+"</span></div>"));i._popup.close(0);i._popup.open(200,b?d.EndTop:d.BeginTop,b?d.EndBottom:d.BeginBottom,i.getFocusDomRef(),null,null,function(){i._popup.close()})}};sap.m.Input.prototype.setValueState=function(v){var O=this.getValueState();sap.m.InputBase.prototype.setValueState.apply(this,arguments);var n=this.getValueState();if(this.getDomRef()&&n!=O&&this.getFocusDomRef()===document.activeElement){switch(n){case sap.ui.core.ValueState.Error:case sap.ui.core.ValueState.Warning:o(this);break;default:c(this)}}return this};sap.m.Input.prototype.setValueStateText=function(t){jQuery.sap.byId(this.getId()+"-message-text").text(t);return this.setProperty("valueStateText",t,true)};sap.m.Input.prototype.onfocusin=function(e){o(this)};sap.m.Input.prototype.onkeydown=function(e){c(this)};sap.m.Input.prototype.onfocusout=function(e){c(this)}})();
