/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.ObjectListItemRenderer");jQuery.sap.require("sap.ui.core.Renderer");jQuery.sap.require("sap.m.ListItemBaseRenderer");jQuery.sap.require("sap.m.ObjectAttribute");sap.m.ObjectListItemRenderer=sap.ui.core.Renderer.extend(sap.m.ListItemBaseRenderer);
sap.m.ObjectListItemRenderer.renderAttributeStatus=function(r,l,a,s){if(!a&&!s||(a&&a._isEmpty()&&s&&s._isEmpty())){return}r.write("<div");r.addClass("sapMObjLAttrRow");r.writeClasses();r.write(">");if(a&&!a._isEmpty()){r.write("<div");r.addClass("sapMObjLAttrDiv");r.writeClasses();if(!s||s._isEmpty()){r.addStyle("width","100%");r.writeStyles()}r.write(">");r.renderControl(a);r.write("</div>")}if(s&&(!s._isEmpty())){r.write("<div");r.addClass("sapMObjLStatusDiv");r.writeClasses();if(!a||a._isEmpty()){r.addStyle("width","100%");r.writeStyles()}r.write(">");r.renderControl(s);r.write("</div>")}r.write("</div>")};
sap.m.ObjectListItemRenderer.renderLIAttributes=function(r,l){r.addClass("sapMObjLItem");r.addClass("sapMObjLListModeDiv")};
sap.m.ObjectListItemRenderer.renderLIContent=function(r,l){r.write("<div");r.writeControlData(l);r.write(">");if(l.getIntro()){r.write("<div");r.addClass("sapMObjLIntro");r.writeClasses();r.writeAttribute("id",l.getId()+"-intro");r.write(">");r.write("<span>");r.writeEscaped(l.getIntro());r.write("</span>");r.write("</div>")}r.write("<div");r.addClass("sapMObjLTopRow");r.writeClasses();r.write(">");r.write("<div");r.addClass("sapMObjLNumberDiv");r.writeClasses();r.write(">");if(l.getNumber()){r.write("<div");r.writeAttribute("id",l.getId()+"-number");r.addClass("sapMObjLNumber");r.writeClasses();r.write(">");r.writeEscaped(l.getNumber());r.write("</div>");if(l.getNumberUnit()){r.write("<div");r.writeAttribute("id",l.getId()+"-numberUnit");r.addClass("sapMObjLNumberUnit");r.writeClasses();r.write(">");r.writeEscaped(l.getNumberUnit());r.write("</div>")}}r.write("</div>");r.write("<div");r.writeAttribute("id",l.getId()+"-title");r.addClass("sapMObjLTitle");r.writeClasses();r.write(">");if(l.getIcon()){r.renderControl(l._getImage())}if(l.getTitle()){r.writeEscaped(l.getTitle())}r.write("</div>");r.write("</div>");r.write('<div style="clear:both"/>');if(l._hasBottomContent()){r.write("<div");r.addClass("sapMObjLBottomRow");r.writeClasses();r.write(">");var a=l.getAttributes();var A=a&&a.length?a.length:0;if(A>0){this.renderAttributeStatus(r,l,a[0],l.getFirstStatus())}else{this.renderAttributeStatus(r,l,null,l.getFirstStatus())}if(A>1){this.renderAttributeStatus(r,l,a[1],l.getSecondStatus())}else{this.renderAttributeStatus(r,l,null,l.getSecondStatus())}for(var i=2;i<A;i++){this.renderAttributeStatus(r,l,a[i])}r.write("</div>")}r.write("</div>")};
