/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.me.CalendarRenderer");sap.me.CalendarRenderer={};
sap.me.CalendarRenderer.render=function(r,c){if(!c.getVisible())return;r.write("<div");r.writeControlData(c);r.addClass("sapMeCalendar");var C="sapMeCalendar"+c.getDesign();r.addClass(C);r.writeClasses();var w=c.getWidth();if(w!=undefined){r.addStyle("width",w);r.writeStyles()}r.write(">");r.renderControl(c._oPrevBtn);r.renderControl(c._oNextBtn);var s=c.getSingleRow();var a=c.getCurrentDate();var m=s?1:c.getMonthsToDisplay();var n=new Date();var N=n.toDateString();if(m===1){this._renderMonth(r,c,a,N)}else{var b=new Date(a);var M=Math.floor(m/2);for(var i=0;i<M;i++){b.setDate(0);b.setDate(1)}for(var i=0;i<m;i++){this._renderMonth(r,c,b.toDateString(),N);b.setDate(32);b.setDate(1)}}r.write("</div>")};
sap.me.CalendarRenderer._renderMonth=function(r,c,m,d){var s=c.getSingleRow();var f=c.getFirstDayOffset();var w=c._WEEKDAYS;var W=w.length;var a=c.getWeeksPerRow();var D=a*W;var b=(100/D);var e=c.getDayHeight();var M=(100/(s?1:c.getMonthsPerRow()));var g=new Date(m);var C=g.getDate();var h=g.getDay();g.setDate(1);var j=g.getDay();var k=g.getMonth();var l=new Date(g.getYear(),k+1,0);var n=l.getDate();var o=s?h+1-f:C+j-f;var p=Math.ceil((n+o-C)/7);var t=s?D:(p*7);var q=c._MONTHS[g.getMonth()]+" "+g.getFullYear();g.setDate(C-o+1);if(s){var u=new Date(g.getTime());u.setDate(u.getDate()+t-1);var F=g.getFullYear();var L=u.getFullYear();var v=g.getMonth();var x=u.getMonth();var y=g.getDate();var z=u.getDate();if(F!=L){q=y+" "+c._MONTHS[v]+" "+F+" - "+z+" "+c._MONTHS[x]+" "+L}else if(v!=x){q=y+" "+c._MONTHS[v]+" - "+z+" "+c._MONTHS[x]+" "+L}else{q=y+" - "+z+" "+c._MONTHS[x]+" "+L}}r.write('<div');r.addClass("sapMeCalendarMonth");if(!s){r.addClass("sapMeCalendarMonthNotSingle")}r.writeClasses();r.addStyle("width",M+"%");r.writeStyles();r.write(">");r.write('<div');r.addClass("sapMeCalendarMonthName");r.writeClasses();if(c.getHideMonthTitles()){r.addStyle("display","none");r.writeStyles()}r.write(">");r.writeEscaped(q);r.write("</div>");r.write('<div');r.addClass("sapMeCalendarMonthDayNames");r.writeClasses();r.write(">");for(var i=0;i<D;i++){var A=w[(i+f)%W];this._renderDay(r,c,null,A,b)}r.write('</div>');r.write('<div');r.addClass("sapMeCalendarMonthDays");r.writeClasses();r.write(">");for(var i=0;i<t;i++){var B=g.getMonth();var E=g.getDay();var h=g.getDate();var N=B!==k;var I=g.toDateString();var G=I==d;this._renderDay(r,c,I,h+"",b,e,E,N,G);g.setDate(g.getDate()+1)}r.write('</div>');r.write('</div>')};
sap.me.CalendarRenderer._renderDay=function(r,c,i,C,d,D,a,n,I){r.write("<div");r.addClass("sapMeCalendarMonthDay");if(I){r.addClass("sapMeCalendarDayNow")}if(n&&!c.getSingleRow()){r.addClass("sapMeCalendarDayNotInCurrentMonth")}if(typeof a=="number"){r.addClass("sapMeCalendarWeekDay"+a)}r.writeClasses();r.addStyle("width",d+"%");if(D){r.addStyle("height",D+"px")}r.writeStyles();r.write(">");r.write('<span>');r.writeEscaped(C);r.write("</span>");r.write('<input type="hidden" value="'+i+'">');r.write("</span>");r.write("</div>")};
