/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.model.odata.ODataListBinding");jQuery.sap.require("sap.ui.model.odata.Filter");jQuery.sap.require("sap.ui.model.ListBinding");jQuery.sap.require("sap.ui.model.ChangeReason");jQuery.sap.require("sap.ui.core.format.DateFormat");sap.ui.model.ListBinding.extend("sap.ui.model.odata.ODataListBinding",{constructor:function(m,p,c,s,f,P){sap.ui.model.ListBinding.apply(this,arguments);this.sFilterParams=null;this.sSortParams=null;this.sRangeParams=null;this.sCustomParams=this.oModel.createCustomParams(this.mParameters);this.aPredefinedFilters=f;this.iStartIndex=0;this.bPendingChange=false;this.aKeys=[];this.bInitialized=false;this.oEntityType=this._getEntityType();this.oDateTimeFormat=sap.ui.core.format.DateFormat.getDateInstance({pattern:"'datetime'''yyyy-MM-dd'T'HH:mm:ss''"});this.oDateTimeOffsetFormat=sap.ui.core.format.DateFormat.getDateInstance({pattern:"'datetimeoffset'''yyyy-MM-dd'T'HH:mm:ss'Z'''"});this.createSortParams(this.oSorter);this.createFilterParams(this.aFilters);var r=this.oModel._getObject(p,c);if(jQuery.isArray(r)){this.aKeys=r;this.iLength=r.length;this.bLengthFinal=true}else{this.iLength=0;this.bLengthFinal=false;if(this.oModel.isCountSupported()){this._getLength()}}},metadata:{publicMethods:["getLength"]}});
sap.ui.model.odata.ODataListBinding.prototype.getContexts=function(s,l,t){this.bInitialized=true;this.iLastLength=l;this.iLastStartIndex=s;this.iLastThreshold=t;if(!s){s=0}if(!l){l=this.oModel.iSizeLimit;if(this.bLengthFinal&&this.iLength<l){l=this.iLength}}if(!t){t=0}var L=true,c=this._getContexts(s,l,t),C={},S;for(var i=0;i<c.length;i++){C[c[i].getPath()]=c[i].getObject()}S=this.calculateSection(s,l,t,c);L=c.length!=l&&!(this.bLengthFinal&&c.length>=this.iLength-s);if(!this.bPendingRequest&&S.length>0&&(L||l<S.length)){this.loadData(S.startIndex,S.length)}if(this.bUseExtendedChangeDetection&&this.aLastContexts&&s<this.iLastEndIndex){var a=this;var d=jQuery.sap.arrayDiff(this.aLastContexts,c,function(o,n){return jQuery.sap.equal(o&&a.oLastContextData&&a.oLastContextData[o.getPath()],n&&C&&C[n.getPath()])});c.diff=d}this.iLastEndIndex=s+l;this.aLastContexts=c.slice(0);this.oLastContextData=jQuery.extend(true,{},C);return c};
sap.ui.model.odata.ODataListBinding.prototype._getContexts=function(s,l,t){var c=[],C,k;if(!s){s=0}if(!l){l=this.oModel.iSizeLimit;if(this.bLengthFinal&&this.iLength<l){l=this.iLength}}if(!t){t=0}for(var i=s;i<s+l;i++){k=this.aKeys[i];if(!k){break}C=this.oModel.getContext(k);c.push(C)}return c};
sap.ui.model.odata.ODataListBinding.prototype.calculateSection=function(s,l,t,c){var L=false,S,a,p,P,r,o={},k;a=s;S=0;for(var i=s;i>=Math.max(s-t,0);i--){k=this.aKeys[i];if(!k){P=i+1;break}}for(var j=s+l;j<s+l+t;j++){k=this.aKeys[j];if(!k){p=j;break}}r=s-P;if(P&&s>t&&r<t){if(c.length!=l){a=s-t}else{a=P-t}S=t}if(a==s){a+=c.length}if(c.length!=l){S+=l-c.length}r=p-s-l;if(r==0){S+=t}if(p&&r<t&&r>0){if(a>=s){a=p;S+=t}}if(this.bLengthFinal&&this.iLength<(S+a)){S=this.iLength-a}o.startIndex=a;o.length=S;return o};
sap.ui.model.odata.ODataListBinding.prototype.setContext=function(c){if(this.oContext!=c){this.oContext=c;this.oEntityType=this._getEntityType();if(this.bInitialized){var r=this.oModel._getObject(this.sPath,this.oContext);if(jQuery.isArray(r)){this.aKeys=r;this.iLength=r.length;this.bLengthFinal=true}else{this.aKeys=[];this.iLength=0;this.bLengthFinal=false;if(this.oModel.isCountSupported()){this._getLength()}}this._fireChange()}}};
sap.ui.model.odata.ODataListBinding.prototype.loadData=function(s,l){var t=this;if(s||l){this.sRangeParams="$skip="+s+"&$top="+l;this.iStartIndex=s}else{s=this.iStartIndex}var p=[];if(this.sRangeParams){p.push(this.sRangeParams)}if(this.sSortParams){p.push(this.sSortParams)}if(this.sFilterParams){p.push(this.sFilterParams)}if(this.sCustomParams){p.push(this.sCustomParams)}p.push("$inlinecount=allpages");function S(d){jQuery.each(d.results,function(i,a){t.aKeys[s+i]=t.oModel._getKey(a)});if(d.__count){t.iLength=parseInt(d.__count,10);t.bLengthFinal=true}if(t.iLength<s+d.results.length){t.iLength=s+d.results.length;t.bLengthFinal=false}if(d.results.length<l||l===undefined){t.iLength=s+d.results.length;t.bLengthFinal=true}if(d.results.length==0){t.iLength=0;t.bLengthFinal=true}t.oRequestHandle=null;t.bPendingRequest=false}function e(E){t.oRequestHandle=null;t.bPendingRequest=false}function u(h){t.oRequestHandle=h}var P=this.sPath,c=this.oContext,I=!jQuery.sap.startsWith(P,"/");if(I){if(c){P=c+"/"+P}else{P=this.oModel.isLegacySyntax()?"/"+P:undefined}}if(P){this.bPendingRequest=true;this.oModel._loadData(P,p,S,e,this.getContext(),false,u)}};
sap.ui.model.odata.ODataListBinding.prototype.getLength=function(){return this.iLength};
sap.ui.model.odata.ODataListBinding.prototype._getLength=function(){var t=this;var p=[];if(this.sFilterParams){p.push(this.sFilterParams)}function _(d){t.iLength=parseInt(d,10);t.bLengthFinal=true}function a(x,e,E){jQuery.sap.log.warning("Request for $count failed: "+e,x.responseText+","+x.status+","+x.statusText)}var P=this.sPath,c=this.oContext,i=!jQuery.sap.startsWith(P,"/");if(i){if(c){P=c+"/"+P}else{P=this.oModel.isLegacySyntax()?"/"+P:undefined}}if(P){var r=this.oModel._createRequest(P+"/$count",p,false);jQuery.ajax({url:r.requestUri,async:r.async,cache:this.oModel.bCache,username:r.user,password:r.password,success:_,error:a})}};
sap.ui.model.odata.ODataListBinding.prototype.checkUpdate=function(f,e){if(!this.bUseExtendedChangeDetection){this._fireChange(e)}else{var c=false;var t=this;if(this.aLastContexts&&this.aLastContexts.length==0){c=true}else if(this.aLastContexts){var C=this._getContexts(this.iLastStartIndex,this.iLastLength,this.iLastThreshold);if(this.aLastContexts.length!=C.length){c=true}else{jQuery.each(this.aLastContexts,function(i,o){if(!jQuery.sap.equal(C[i].getObject(),t.oLastContextData[o.getPath()])){c=true;return false}})}}if(c||f){if(!e){e={reason:sap.ui.model.ChangeReason.Change}}this._fireChange(e)}}};
sap.ui.model.odata.ODataListBinding.prototype.sort=function(s){this.createSortParams(s);this.aKeys=[];if(this.bInitialized){if(this.oRequestHandle){this.oRequestHandle.abort();this.oRequestHandle=null;this.bPendingRequest=false}this._fireChange({reason:sap.ui.model.ChangeReason.Sort});this._fireSort({sorter:s})}return this};
sap.ui.model.odata.ODataListBinding.prototype.createSortParams=function(s){if(s){this.sSortParams="$orderby="+s.sPath;this.sSortParams+=s.bDescending?"%20desc":"%20asc"}else{this.sSortParams=null}};
sap.ui.model.odata.ODataListBinding.prototype.filter=function(f){if(!f){f=[]}if(this.aPredefinedFilters){f=f.concat(this.aPredefinedFilters)}this.createFilterParams(f);this.aKeys=[];this.iLength=0;this.bLengthFinal=false;if(this.oModel.isCountSupported()){this._getLength()}if(this.bInitialized){if(this.oRequestHandle){this.oRequestHandle.abort();this.oRequestHandle=null;this.bPendingRequest=false}this._fireChange({reason:sap.ui.model.ChangeReason.Filter});this._fireFilter({filters:f})}return this};
sap.ui.model.odata.ODataListBinding.prototype.createFilterParams=function(f){if(f&&f.length>0){var F={},a=0,b,s="$filter=",c=0,t=this;jQuery.each(f,function(j,o){b=F[o.sPath];if(!b){b=F[o.sPath]=[];a++}b.push(o)});jQuery.each(F,function(p,b){if(b.length>1){s+='('}jQuery.each(b,function(i,o){if(o instanceof sap.ui.model.odata.Filter){if(o.aValues.length>1){s+='('}jQuery.each(o.aValues,function(i,d){if(i>0){if(o.bAND){s+="%20and%20"}else{s+="%20or%20"}}s=t._createFilterSegment(o.sPath,d.operator,d.value1,d.value2,s)});if(o.aValues.length>1){s+=')'}}else{s=t._createFilterSegment(o.sPath,o.sOperator,o.oValue1,o.oValue2,s)}if(i<b.length-1){s+="%20or%20"}});if(b.length>1){s+=')'}if(c<a-1){s+="%20and%20"}c++});this.sFilterParams=s}else{this.sFilterParams=null}};
sap.ui.model.odata.ODataListBinding.prototype._createFilterSegment=function(p,o,v,V,f){var P;if(this.oEntityType){P=this.oModel.oMetadata._getPropertyMetadata(this.oEntityType,p)}if(P){switch(P.type){case"Edm.String":v="'"+String(v).replace(/'/g,"''")+"'";V=(V)?"'"+String(V).replace(/'/g,"''")+"'":null;break;case"Edm.Time":v="time'"+v+"'";V=(V)?"time'"+V+"'":null;break;case"Edm.DateTime":v=this.oDateTimeFormat.format(new Date(v),true);V=(V)?this.oDateTimeFormat.format(new Date(V),true):null;break;case"Edm.DateTimeOffset":v=this.oDateTimeOffsetFormat.format(new Date(v),true);V=(V)?this.oDateTimeOffsetFormat.format(new Date(V),true):null;break;case"Edm.Guid":v="guid'"+v+"'";V=(V)?"guid'"+V+"'":null;break;case"Edm.Binary":v="binary'"+v+"'";V=(V)?"binary'"+V+"'":null;break;default:break}}else{}if(v){v=jQuery.sap.encodeURL(String(v))}if(V){V=jQuery.sap.encodeURL(String(V))}switch(o){case"EQ":case"NE":case"GT":case"GE":case"LT":case"LE":f+=p+"%20"+o.toLowerCase()+"%20"+v;break;case"BT":f+="("+p+"%20ge%20"+v+"%20and%20"+p+"%20le%20"+V+")";break;case"Contains":f+="substringof("+v+","+p+")";break;case"StartsWith":f+="startswith("+p+","+v+")";break;case"EndsWith":f+="endswith("+p+","+v+")";break;default:f+="true"}return f};
sap.ui.model.odata.ODataListBinding.prototype._getEntityType=function(){var r=this.oModel.resolve(this.sPath,this.oContext);if(r){return this.oModel.oMetadata._getEntityTypeByPath(r)}return undefined};
sap.ui.model.odata.ODataListBinding.prototype._refresh=function(){this.aKeys=[];this.bLengthFinal=false;this.iLength=0;this.checkUpdate()};
