/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.model.odata.ODataMetadata");sap.ui.base.Object.extend("sap.ui.model.odata.ODataMetadata",{constructor:function(m){this.oMetadata=m},metadata:{publicMethods:["getServiceMetadata"]}});
sap.ui.model.odata.ODataMetadata.prototype.getServiceMetadata=function(){return this.oMetadata};
sap.ui.model.odata.ODataMetadata.prototype._getEntityTypeByPath=function(p){if(!p){return null}if(!this.oMetadata||jQuery.isEmptyObject(this.oMetadata)){return null}var c=p.replace(/^\/|\/$/g,""),P=c.split("/"),l=P.length,a,A,o,e,E,b,t=this;if(P[0].indexOf("(")!=-1){P[0]=P[0].substring(0,P[0].indexOf("("))}if(l>1){o=t._getEntityTypeByPath(P[0]);for(var i=1;i<P.length;i++){if(o){if(P[i].indexOf("(")!=-1){P[i]=P[i].substring(0,P[i].indexOf("("))}if(o.navigationProperty){jQuery.each(o.navigationProperty,function(j,n){if(n.name===P[i]){a=t._splitName(n.relationship);A=t._getObjectMetadata("association",a[0],a[1]);if(A){e=A.end[0];if(e.role!==n.toRole){e=A.end[1]}E=t._splitName(e.type);o=t._getObjectMetadata("entityType",E[0],E[1])}return false}})}b=o}}}else{E=this._splitName(this._getEntityTypeName(P[0]));b=this._getObjectMetadata("entityType",E[0],E[1])}return b};
sap.ui.model.odata.ODataMetadata.prototype._splitName=function(f){var p=[];if(f){var s=f.lastIndexOf(".");p[0]=f.substr(s+1);p[1]=f.substr(0,s)}return p};
sap.ui.model.odata.ODataMetadata.prototype._getEntityTypeName=function(c){var e;if(c){jQuery.each(this.oMetadata.dataServices.schema,function(i,s){if(s.entityContainer){jQuery.each(s.entityContainer,function(k,E){jQuery.each(E.entitySet,function(j,o){if(o.name===c){e=o.entityType;return false}})})}})}return e};
sap.ui.model.odata.ODataMetadata.prototype._getObjectMetadata=function(o,O,n){var a;if(O&&n){jQuery.each(this.oMetadata.dataServices.schema,function(i,s){if(s[o]&&s.namespace===n){jQuery.each(s[o],function(j,c){if(c.name===O){a=c;return false}});return!a}})}return a};
sap.ui.model.odata.ODataMetadata.prototype._getPropertyMetadata=function(e,p){var P;var a=p.split("/");jQuery.each(e.property,function(k,o){if(o.name===a[0]){P=o;return false}});if(P&&a.length>1&&!jQuery.sap.startsWith(P.type.toLowerCase(),"edm.")){var n=this._splitName(P.type);P=this._getPropertyMetadata(this._getObjectMetadata("complexType",n[0],n[1]),a[1])}return P};
