/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.model.xml.XMLListBinding");jQuery.sap.require("sap.ui.model.ListBinding");jQuery.sap.require("sap.ui.model.ChangeReason");sap.ui.model.ListBinding.extend("sap.ui.model.xml.XMLListBinding",{constructor:function(m,p,c,s,f,P){sap.ui.model.ListBinding.apply(this,arguments);this.update()},metadata:{publicMethods:["getLength"]}});
sap.ui.model.xml.XMLListBinding.prototype.getContexts=function(s,l){this.iLastStartIndex=s;this.iLastLength=l;if(!s){s=0}if(!l){l=Math.min(this.iLength,this.oModel.iSizeLimit)}var c=this._getContexts(s,l),C={};for(var i=0;i<c.length;i++){C[c[i].getPath()]=this.oModel._getObject(c[i].getPath())[0]}if(this.bUseExtendedChangeDetection&&this.aLastContexts&&s<this.iLastEndIndex){var t=this;var d=jQuery.sap.arrayDiff(this.aLastContexts,c,function(o,n){var O=t.oLastContextData&&t.oLastContextData[o.getPath()];var N=C&&C[n.getPath()];if(O&&N){return jQuery.sap.isEqualNode(O,N)}return false});c.diff=d}this.iLastEndIndex=s+l;this.aLastContexts=c.slice(0);this.oLastContextData={};var t=this;jQuery.each(C,function(k,n){t.oLastContextData[k]=n.cloneNode(true)});return c};
sap.ui.model.xml.XMLListBinding.prototype._getContexts=function(s,l){if(!s){s=0}if(!l){l=Math.min(this.iLength,this.oModel.iSizeLimit)}var e=Math.min(s+l,this.aIndices.length),c,C=[],p=this.oModel.resolve(this.sPath,this.oContext)+"/";for(var i=s;i<e;i++){c=this.oModel.getContext(p+this.aIndices[i]);C.push(c)}return C};
sap.ui.model.xml.XMLListBinding.prototype.setContext=function(c){if(this.oContext!=c){this.oContext=c;this.update();this._fireChange({reason:sap.ui.model.ChangeReason.Context})}};
sap.ui.model.xml.XMLListBinding.prototype.getLength=function(){return this.iLength};
sap.ui.model.xml.XMLListBinding.prototype._getLength=function(){return this.aIndices.length};
sap.ui.model.xml.XMLListBinding.prototype.update=function(){var l=this.oModel._getObject(this.sPath,this.oContext);if(l){this.oList=[];var t=this;if(this.bUseExtendedChangeDetection){jQuery.each(l,function(k,n){t.oList.push(n.cloneNode(true))})}else{this.oList=l.slice(0)}this.updateIndices();this.applyFilter();this.applySort();this.iLength=this._getLength()}else{this.oList=null;this.aIndices=[];this.iLength=0}};
sap.ui.model.xml.XMLListBinding.prototype.checkUpdate=function(f){if(!this.bUseExtendedChangeDetection){var l=this.oModel._getObject(this.sPath,this.oContext);if(!this.oList||!l||l.length!=this.oList.length||f){this.update();this._fireChange({reason:sap.ui.model.ChangeReason.Change})}}else{var c=false;var t=this;var l=this.oModel._getObject(this.sPath,this.oContext);if(!jQuery.sap.equal(this.oList,l)){this.update()}var C=this._getContexts(this.iLastStartIndex,this.iLastLength);if(this.aLastContexts){if(this.aLastContexts.length!=C.length){c=true}else{jQuery.each(this.aLastContexts,function(i,o){var n=C[i].getObject()[0];var O=t.oLastContextData&&t.oLastContextData[o.getPath()];if(n&&O&&!O.isEqualNode(n)){c=true;return false}})}}else{c=true}if(c||f){this._fireChange({reason:sap.ui.model.ChangeReason.Change})}}};
sap.ui.model.xml.XMLListBinding.prototype.updateIndices=function(){this.aIndices=[];for(var i=0;i<this.oList.length;i++){this.aIndices.push(i)}};
sap.ui.model.xml.XMLListBinding.prototype.sort=function(s){if(!s){this.oSorter=null;this.updateIndices();this.applyFilter()}else{this.oSorter=s;this.applySort()}this._fireChange({reason:sap.ui.model.ChangeReason.Sort});this._fireSort({sorter:s});return this};
sap.ui.model.xml.XMLListBinding.prototype.applySort=function(){if(!this.oSorter){return}var t=this,s=[],v,c=this.oSorter.fnCompare;if(!c){c=function(a,b){if(b==null){return-1}if(a==null){return 1}if(typeof a=="string"&&typeof b=="string"){return a.localeCompare(b)}if(a<b){return-1}if(a>b){return 1}return 0}}jQuery.each(this.aIndices,function(i,I){v=t.oModel.getProperty(t.oSorter.sPath,t.oList[I]);if(typeof v=="string"){v=v.toLocaleUpperCase()}s[I]=v});this.aIndices.sort(function(a,b){var d=s[a],e=s[b],r=c(d,e);if(t.oSorter.bDescending){r=-r}return r})};
sap.ui.model.xml.XMLListBinding.prototype.filter=function(f){this.updateIndices();if(!f||!jQuery.isArray(f)||f.length==0){this.aFilters=null;this.iLength=this._getLength()}else{this.aFilters=f;this.applyFilter()}this.applySort();this._fireChange({reason:sap.ui.model.ChangeReason.Filter});this._fireFilter({filters:f});return this};
sap.ui.model.xml.XMLListBinding.prototype.applyFilter=function(){if(!this.aFilters){return}var t=this,f={},F,a=[],g=false,b=true;jQuery.each(this.aIndices,function(i,I){b=true;jQuery.each(t.aFilters,function(j,o){F=f[o.sPath];if(!F){F=f[o.sPath]=[]}F.push(o)});jQuery.each(f,function(p,F){var v=t.oModel.getProperty(p,t.oList[I]);if(typeof v=="string"){v=v.toUpperCase()}g=false;jQuery.each(F,function(j,o){var T=t.getFilterFunction(o);if(v!=undefined&&T(v)){g=true;return false}});if(!g){b=false;return false}});if(b){a.push(I)}});this.aIndices=a;this.iLength=a.length};
sap.ui.model.xml.XMLListBinding.prototype.getFilterFunction=function(f){if(f.fnTest){return f.fnTest}var v=f.oValue1,V=f.oValue2;if(typeof v=="string"){v=v.toUpperCase()}if(typeof V=="string"){V=V.toUpperCase()}switch(f.sOperator){case"EQ":f.fnTest=function(a){return a==v};break;case"NE":f.fnTest=function(a){return a!=v};break;case"LT":f.fnTest=function(a){return a<v};break;case"LE":f.fnTest=function(a){return a<=v};break;case"GT":f.fnTest=function(a){return a>v};break;case"GE":f.fnTest=function(a){return a>=v};break;case"BT":f.fnTest=function(a){return(a>=v)&&(a<=V)};break;case"Contains":f.fnTest=function(a){return a.indexOf(v)!=-1};break;case"StartsWith":f.fnTest=function(a){return a.indexOf(v)==0};break;case"EndsWith":f.fnTest=function(a){var p=a.indexOf(v);if(p==-1){return false}return p==a.length-new String(f.oValue1).length};break;default:f.fnTest=function(a){return true}}return f.fnTest};
sap.ui.model.xml.XMLListBinding.prototype.getDistinctValues=function(p){var r=[],m={},v,t=this;jQuery.each(this.oList,function(i,c){v=t.oModel.getProperty(p,c);if(!m[v]){m[v]=true;r.push(v)}});return r};
