/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.viz.ui5.core.BaseChart");jQuery.sap.require("sap.viz.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.viz.ui5.core.BaseChart",{metadata:{"abstract":true,library:"sap.viz",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:'640px'},"height":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:'480px'},"css":{type:"string",group:"Appearance",defaultValue:null}},aggregations:{"dataset":{type:"sap.viz.ui5.data.Dataset",multiple:false},"noData":{type:"sap.ui.core.Control",multiple:false}},events:{"beforeCreateViz":{}}}});sap.viz.ui5.core.BaseChart.M_EVENTS={'beforeCreateViz':'beforeCreateViz'};jQuery.sap.require("sap.viz.ui5.core.BaseStructuredType");
sap.viz.ui5.core.BaseChart.prototype.init=function(){sap.viz._initializeVIZ();this._mVIZHandler={}};
sap.viz.ui5.core.BaseChart.prototype.exit=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);delete this._sResizeListenerId}if(this._oVIZInstance){this._oVIZInstance.destroy();delete this._oVIZInstance}};
sap.viz.ui5.core.BaseChart.prototype.onBeforeRendering=function(){if(this._sResizeListenerId){sap.ui.core.ResizeHandler.deregister(this._sResizeListenerId);delete this._sResizeListenerId}};
sap.viz.ui5.core.BaseChart.prototype.onAfterRendering=function(){if(!sap.viz.__svg_support||!this.getDataset()||!this.getDataset().getVIZDataset()){return}if(this._oVIZInstance){this._oVIZInstance.destroy();delete this._oVIZInstance}var u={type:this.getVIZChartType(),data:this.getDataset().getVIZDataset(),container:this.getDomRef(),css:this.getCss(),options:this._getOptions()};this.fireBeforeCreateViz({usrOptions:u});this._oVIZInstance=sap.viz.core.createViz(u);var t=this;jQuery.sap.forIn(this._mVIZHandler,function(n,h){t._oVIZInstance.on(n+sap.viz.ui5.core.BaseChart.EVENT_SUFFIX,h)});this._sResizeListenerId=sap.ui.core.ResizeHandler.register(this.getDomRef(),jQuery.proxy(this.onresize,this))};
sap.viz.ui5.core.BaseChart.prototype.onresize=function(o){var s={width:this.$().width(),height:this.$().height()};if(this._oVIZInstance){this._oVIZInstance.size(s)}};
sap.viz.ui5.core.BaseChart.prototype.setDefaultSelection=function(s){var d=this.getDataset();if(d){var v=this.getDataset().getVIZDataset();if(v){v.info({'type':'defaultSelection','value':s});if(this._oVIZInstance){this._oVIZInstance.data(v)}}}};
sap.viz.ui5.core.BaseChart.EVENT_SUFFIX=".sap.viz.ui5.core";sap.viz.ui5.core.BaseChart.prototype._getOrCreate=sap.viz.ui5.core.BaseStructuredType.prototype._getOrCreate;sap.viz.ui5.core.BaseChart.prototype._getOptions=sap.viz.ui5.core.BaseStructuredType.prototype._getOptions;
sap.viz.ui5.core.BaseChart.prototype._attachVIZEvent=function(n,d,h,l){var t=this;if(!this.hasListeners(n)){this._mVIZHandler[n]=function(o){t.fireEvent(n,o)};if(this._oVIZInstance){this._oVIZInstance.on(n+sap.viz.ui5.core.BaseChart.EVENT_SUFFIX,this._mVIZHandler[n])}}sap.ui.core.Control.prototype.attachEvent.apply(this,arguments);return this};
sap.viz.ui5.core.BaseChart.prototype._detachVIZEvent=function(n,d,h,l){sap.ui.core.Control.prototype.detachEvent.apply(this,arguments);if(!this.hasListeners(n)){if(this._oVIZInstance){this._oVIZInstance.on(n+sap.viz.ui5.core.BaseChart.EVENT_SUFFIX,null)}delete this._mVIZHandler[n]}return this};
sap.viz.ui5.core.BaseChart.prototype.getVIZInstance=function(){return this._oVIZInstance||null};
